// Database met industriële kettingen volgens internationale normen (ISO 606, ANSI B29.1, DIN 8187, DIN 8188, ISO 4347, DIN 8181, DIN 8167, EN 818).
// Bevat specifieke illustraties voor elke kettingfamilie (Simplex, Duplex, Triplex, Fleyer/Leaf, Double Pitch, Heavy Conveyor, Slatband, Ronde Schalm).

const CHAINS_DB = [
  {
    "designation": "04B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 6,
    "width": 2.8,
    "rollerDiameter": 4,
    "pinDiameter": 1.85,
    "innerPlateHeight": 5,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "04B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 6,
    "width": 2.8,
    "rollerDiameter": 4,
    "pinDiameter": 1.85,
    "innerPlateHeight": 5,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "05B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 8,
    "width": 3,
    "rollerDiameter": 5,
    "pinDiameter": 2.31,
    "innerPlateHeight": 7.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "05B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 8,
    "width": 3,
    "rollerDiameter": 5,
    "pinDiameter": 2.31,
    "innerPlateHeight": 7.1,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "06B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 9.525,
    "width": 5.72,
    "rollerDiameter": 6.35,
    "pinDiameter": 3.28,
    "innerPlateHeight": 8.2,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "06B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 9.525,
    "width": 5.72,
    "rollerDiameter": 6.35,
    "pinDiameter": 3.28,
    "innerPlateHeight": 8.2,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "06B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 9.525,
    "width": 5.72,
    "rollerDiameter": 6.35,
    "pinDiameter": 3.28,
    "innerPlateHeight": 8.2,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "08B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 7.75,
    "rollerDiameter": 8.51,
    "pinDiameter": 4.45,
    "innerPlateHeight": 11.8,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "08B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 12.7,
    "width": 7.75,
    "rollerDiameter": 8.51,
    "pinDiameter": 4.45,
    "innerPlateHeight": 11.8,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "08B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 12.7,
    "width": 7.75,
    "rollerDiameter": 8.51,
    "pinDiameter": 4.45,
    "innerPlateHeight": 11.8,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "10B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 15.875,
    "width": 9.65,
    "rollerDiameter": 10.16,
    "pinDiameter": 5.08,
    "innerPlateHeight": 14.7,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "10B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 15.875,
    "width": 9.65,
    "rollerDiameter": 10.16,
    "pinDiameter": 5.08,
    "innerPlateHeight": 14.7,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "10B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 15.875,
    "width": 9.65,
    "rollerDiameter": 10.16,
    "pinDiameter": 5.08,
    "innerPlateHeight": 14.7,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "12B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 11.68,
    "rollerDiameter": 12.07,
    "pinDiameter": 5.72,
    "innerPlateHeight": 16.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "12B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 19.05,
    "width": 11.68,
    "rollerDiameter": 12.07,
    "pinDiameter": 5.72,
    "innerPlateHeight": 16.1,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "12B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 19.05,
    "width": 11.68,
    "rollerDiameter": 12.07,
    "pinDiameter": 5.72,
    "innerPlateHeight": 16.1,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "16B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 17.02,
    "rollerDiameter": 15.88,
    "pinDiameter": 8.28,
    "innerPlateHeight": 21,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "16B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 25.4,
    "width": 17.02,
    "rollerDiameter": 15.88,
    "pinDiameter": 8.28,
    "innerPlateHeight": 21,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "16B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 25.4,
    "width": 17.02,
    "rollerDiameter": 15.88,
    "pinDiameter": 8.28,
    "innerPlateHeight": 21,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "20B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 19.56,
    "rollerDiameter": 19.05,
    "pinDiameter": 10.19,
    "innerPlateHeight": 26.4,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "20B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 31.75,
    "width": 19.56,
    "rollerDiameter": 19.05,
    "pinDiameter": 10.19,
    "innerPlateHeight": 26.4,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "20B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 31.75,
    "width": 19.56,
    "rollerDiameter": 19.05,
    "pinDiameter": 10.19,
    "innerPlateHeight": 26.4,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "24B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 25.4,
    "rollerDiameter": 25.4,
    "pinDiameter": 14.63,
    "innerPlateHeight": 33.4,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "24B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 38.1,
    "width": 25.4,
    "rollerDiameter": 25.4,
    "pinDiameter": 14.63,
    "innerPlateHeight": 33.4,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "24B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 38.1,
    "width": 25.4,
    "rollerDiameter": 25.4,
    "pinDiameter": 14.63,
    "innerPlateHeight": 33.4,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "28B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 44.45,
    "width": 30.99,
    "rollerDiameter": 27.94,
    "pinDiameter": 15.9,
    "innerPlateHeight": 37,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "28B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 44.45,
    "width": 30.99,
    "rollerDiameter": 27.94,
    "pinDiameter": 15.9,
    "innerPlateHeight": 37,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "28B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 44.45,
    "width": 30.99,
    "rollerDiameter": 27.94,
    "pinDiameter": 15.9,
    "innerPlateHeight": 37,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "32B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 30.99,
    "rollerDiameter": 29.21,
    "pinDiameter": 17.81,
    "innerPlateHeight": 42.2,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "32B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 50.8,
    "width": 30.99,
    "rollerDiameter": 29.21,
    "pinDiameter": 17.81,
    "innerPlateHeight": 42.2,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "32B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 50.8,
    "width": 30.99,
    "rollerDiameter": 29.21,
    "pinDiameter": 17.81,
    "innerPlateHeight": 42.2,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "40B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 63.5,
    "width": 38.1,
    "rollerDiameter": 39.37,
    "pinDiameter": 22.89,
    "innerPlateHeight": 52.96,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "40B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 63.5,
    "width": 38.1,
    "rollerDiameter": 39.37,
    "pinDiameter": 22.89,
    "innerPlateHeight": 52.96,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "40B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 63.5,
    "width": 38.1,
    "rollerDiameter": 39.37,
    "pinDiameter": 22.89,
    "innerPlateHeight": 52.96,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "48B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 76.2,
    "width": 45.72,
    "rollerDiameter": 48.26,
    "pinDiameter": 29.24,
    "innerPlateHeight": 63.8,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "48B-2",
    "norm": "ISO / BS / DIN",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 76.2,
    "width": 45.72,
    "rollerDiameter": 48.26,
    "pinDiameter": 29.24,
    "innerPlateHeight": 63.8,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "48B-3",
    "norm": "ISO / BS / DIN",
    "strand": "Triplex (3-sporig)",
    "strandsCount": 3,
    "pitch": 76.2,
    "width": 45.72,
    "rollerDiameter": 48.26,
    "pinDiameter": 29.24,
    "innerPlateHeight": 63.8,
    "illustrationImg": "chain-triplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "56B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 88.9,
    "width": 53.34,
    "rollerDiameter": 53.98,
    "pinDiameter": 34.32,
    "innerPlateHeight": 76.8,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "64B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 101.6,
    "width": 60.96,
    "rollerDiameter": 63.5,
    "pinDiameter": 39.4,
    "innerPlateHeight": 88,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "72B-1",
    "norm": "ISO / BS / DIN",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 114.3,
    "width": 68.58,
    "rollerDiameter": 72.39,
    "pinDiameter": 44.45,
    "innerPlateHeight": 100,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 25",
    "norm": "ANSI / ASA",
    "strand": "Busketting (1-sporig)",
    "strandsCount": 1,
    "pitch": 6.35,
    "width": 3.18,
    "rollerDiameter": 3.3,
    "pinDiameter": 2.31,
    "innerPlateHeight": 6,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 35",
    "norm": "ANSI / ASA",
    "strand": "Busketting (1-sporig)",
    "strandsCount": 1,
    "pitch": 9.525,
    "width": 4.76,
    "rollerDiameter": 5.08,
    "pinDiameter": 3.58,
    "innerPlateHeight": 9,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 41",
    "norm": "ANSI / ASA",
    "strand": "Smalle lichte serie (1-sporig)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 6.35,
    "rollerDiameter": 7.77,
    "pinDiameter": 3.58,
    "innerPlateHeight": 9.9,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 40",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 7.94,
    "rollerDiameter": 7.92,
    "pinDiameter": 3.96,
    "innerPlateHeight": 12,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 40-2",
    "norm": "ANSI / ASA",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 12.7,
    "width": 7.94,
    "rollerDiameter": 7.92,
    "pinDiameter": 3.96,
    "innerPlateHeight": 12,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 50",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 15.875,
    "width": 9.53,
    "rollerDiameter": 10.16,
    "pinDiameter": 5.08,
    "innerPlateHeight": 15.09,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 50-2",
    "norm": "ANSI / ASA",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 15.875,
    "width": 9.53,
    "rollerDiameter": 10.16,
    "pinDiameter": 5.08,
    "innerPlateHeight": 15.09,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 60",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 12.7,
    "rollerDiameter": 11.91,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 60H",
    "norm": "ANSI / ASA Heavy",
    "strand": "Zware uitvoering (1-sporig)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 12.7,
    "rollerDiameter": 11.91,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 60-2",
    "norm": "ANSI / ASA",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 19.05,
    "width": 12.7,
    "rollerDiameter": 11.91,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18.1,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 80",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 15.88,
    "rollerDiameter": 15.88,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 80H",
    "norm": "ANSI / ASA Heavy",
    "strand": "Zware uitvoering (1-sporig)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 15.88,
    "rollerDiameter": 15.88,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 80-2",
    "norm": "ANSI / ASA",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 25.4,
    "width": 15.88,
    "rollerDiameter": 15.88,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24.1,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 100",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 19.05,
    "rollerDiameter": 19.05,
    "pinDiameter": 9.53,
    "innerPlateHeight": 30.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 100H",
    "norm": "ANSI / ASA Heavy",
    "strand": "Zware uitvoering (1-sporig)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 19.05,
    "rollerDiameter": 19.05,
    "pinDiameter": 9.53,
    "innerPlateHeight": 30.1,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 100-2",
    "norm": "ANSI / ASA",
    "strand": "Duplex (2-sporig)",
    "strandsCount": 2,
    "pitch": 31.75,
    "width": 19.05,
    "rollerDiameter": 19.05,
    "pinDiameter": 9.53,
    "innerPlateHeight": 30.1,
    "illustrationImg": "chain-duplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 120",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 25.4,
    "rollerDiameter": 22.23,
    "pinDiameter": 11.11,
    "innerPlateHeight": 36.2,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 140",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 44.45,
    "width": 25.4,
    "rollerDiameter": 25.4,
    "pinDiameter": 12.7,
    "innerPlateHeight": 42.2,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 160",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 31.75,
    "rollerDiameter": 28.58,
    "pinDiameter": 14.27,
    "innerPlateHeight": 48.2,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 180",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 57.15,
    "width": 35.71,
    "rollerDiameter": 35.71,
    "pinDiameter": 17.46,
    "innerPlateHeight": 54.3,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 200",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 63.5,
    "width": 38.1,
    "rollerDiameter": 39.68,
    "pinDiameter": 19.85,
    "innerPlateHeight": 60.3,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "ANSI 240",
    "norm": "ANSI / ASA",
    "strand": "Simplex (1-sporig)",
    "strandsCount": 1,
    "pitch": 76.2,
    "width": 47.63,
    "rollerDiameter": 47.63,
    "pinDiameter": 23.81,
    "innerPlateHeight": 72.4,
    "illustrationImg": "chain-simplex.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL0822",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 4.45,
    "rollerDiameter": 0,
    "pinDiameter": 4.45,
    "innerPlateHeight": 10.6,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL0844",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 8.9,
    "rollerDiameter": 0,
    "pinDiameter": 4.45,
    "innerPlateHeight": 10.6,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL0866",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (6x6)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 13.35,
    "rollerDiameter": 0,
    "pinDiameter": 4.45,
    "innerPlateHeight": 10.6,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL0888",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (8x8)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 17.8,
    "rollerDiameter": 0,
    "pinDiameter": 4.45,
    "innerPlateHeight": 10.6,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1022",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 15.875,
    "width": 5.08,
    "rollerDiameter": 0,
    "pinDiameter": 5.08,
    "innerPlateHeight": 13.5,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1044",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 15.875,
    "width": 10.16,
    "rollerDiameter": 0,
    "pinDiameter": 5.08,
    "innerPlateHeight": 13.5,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1066",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (6x6)",
    "strandsCount": 1,
    "pitch": 15.875,
    "width": 15.24,
    "rollerDiameter": 0,
    "pinDiameter": 5.08,
    "innerPlateHeight": 13.5,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1222",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 5.72,
    "rollerDiameter": 0,
    "pinDiameter": 5.72,
    "innerPlateHeight": 16.1,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1244",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 11.44,
    "rollerDiameter": 0,
    "pinDiameter": 5.72,
    "innerPlateHeight": 16.1,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1266",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (6x6)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 17.16,
    "rollerDiameter": 0,
    "pinDiameter": 5.72,
    "innerPlateHeight": 16.1,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1622",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 8.28,
    "rollerDiameter": 0,
    "pinDiameter": 8.28,
    "innerPlateHeight": 21,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1644",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 16.56,
    "rollerDiameter": 0,
    "pinDiameter": 8.28,
    "innerPlateHeight": 21,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL1666",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (6x6)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 24.84,
    "rollerDiameter": 0,
    "pinDiameter": 8.28,
    "innerPlateHeight": 21,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL2022",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 10.19,
    "rollerDiameter": 0,
    "pinDiameter": 10.19,
    "innerPlateHeight": 26,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL2044",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 20.38,
    "rollerDiameter": 0,
    "pinDiameter": 10.19,
    "innerPlateHeight": 26,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL2422",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 14.63,
    "rollerDiameter": 0,
    "pinDiameter": 14.63,
    "innerPlateHeight": 33.4,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL2444",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 29.26,
    "rollerDiameter": 0,
    "pinDiameter": 14.63,
    "innerPlateHeight": 33.4,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL2822",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 44.45,
    "width": 15.9,
    "rollerDiameter": 0,
    "pinDiameter": 15.9,
    "innerPlateHeight": 37,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "LL3222",
    "norm": "Fleyer (DIN 8152)",
    "strand": "Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 17.81,
    "rollerDiameter": 0,
    "pinDiameter": 17.81,
    "innerPlateHeight": 42.2,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "AL344",
    "norm": "Fleyer (ANSI AL)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 9.525,
    "width": 5.72,
    "rollerDiameter": 0,
    "pinDiameter": 3.58,
    "innerPlateHeight": 8.6,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "AL444",
    "norm": "Fleyer (ANSI AL)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 8.16,
    "rollerDiameter": 0,
    "pinDiameter": 3.96,
    "innerPlateHeight": 10.4,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "AL544",
    "norm": "Fleyer (ANSI AL)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 15.875,
    "width": 10.16,
    "rollerDiameter": 0,
    "pinDiameter": 5.08,
    "innerPlateHeight": 13,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "AL644",
    "norm": "Fleyer (ANSI AL)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 12.24,
    "rollerDiameter": 0,
    "pinDiameter": 5.94,
    "innerPlateHeight": 15.6,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "AL844",
    "norm": "Fleyer (ANSI AL)",
    "strand": "Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 16.32,
    "rollerDiameter": 0,
    "pinDiameter": 7.92,
    "innerPlateHeight": 20.8,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL422 / LH0822",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 4.45,
    "rollerDiameter": 0,
    "pinDiameter": 5.08,
    "innerPlateHeight": 12,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL444 / LH0844",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 12.7,
    "width": 8.9,
    "rollerDiameter": 0,
    "pinDiameter": 5.08,
    "innerPlateHeight": 12,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL522 / LH1022",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (2x2)",
    "strandsCount": 1,
    "pitch": 15.875,
    "width": 5.08,
    "rollerDiameter": 0,
    "pinDiameter": 5.94,
    "innerPlateHeight": 15,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL634 / LH1234",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (3x4)",
    "strandsCount": 1,
    "pitch": 19.05,
    "width": 12.7,
    "rollerDiameter": 0,
    "pinDiameter": 7.92,
    "innerPlateHeight": 18.1,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL844 / LH1644",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (4x4)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 15.88,
    "rollerDiameter": 0,
    "pinDiameter": 9.53,
    "innerPlateHeight": 24.1,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL846 / LH1646",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (4x6)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 23.82,
    "rollerDiameter": 0,
    "pinDiameter": 9.53,
    "innerPlateHeight": 24.1,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL1046 / LH2046",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (4x6)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 28.58,
    "rollerDiameter": 0,
    "pinDiameter": 11.11,
    "innerPlateHeight": 30.1,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "BL1246 / LH2446",
    "norm": "Fleyer (ANSI BL/LH)",
    "strand": "Zware Leaf Chain (4x6)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 34.29,
    "rollerDiameter": 0,
    "pinDiameter": 12.7,
    "innerPlateHeight": 36.2,
    "illustrationImg": "chain-fleyer.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "A2040",
    "norm": "Double Pitch (DIN 8181)",
    "strand": "Aandrijfserie (Kleine rol)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 7.94,
    "rollerDiameter": 7.92,
    "pinDiameter": 3.96,
    "innerPlateHeight": 12,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "A2050",
    "norm": "Double Pitch (DIN 8181)",
    "strand": "Aandrijfserie (Kleine rol)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 9.53,
    "rollerDiameter": 10.16,
    "pinDiameter": 5.08,
    "innerPlateHeight": 15,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "A2060",
    "norm": "Double Pitch (DIN 8181)",
    "strand": "Aandrijfserie (Kleine rol)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 12.7,
    "rollerDiameter": 11.91,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "A2080",
    "norm": "Double Pitch (DIN 8181)",
    "strand": "Aandrijfserie (Kleine rol)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 15.88,
    "rollerDiameter": 15.88,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2040",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport S-type (Kleine rol)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 7.94,
    "rollerDiameter": 7.92,
    "pinDiameter": 3.96,
    "innerPlateHeight": 12,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2050",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport S-type (Kleine rol)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 9.53,
    "rollerDiameter": 10.16,
    "pinDiameter": 5.08,
    "innerPlateHeight": 15,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2060",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport S-type (Kleine rol)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 12.7,
    "rollerDiameter": 11.91,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2080",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport S-type (Kleine rol)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 15.88,
    "rollerDiameter": 15.88,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2100",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport S-type (Kleine rol)",
    "strandsCount": 1,
    "pitch": 63.5,
    "width": 19.05,
    "rollerDiameter": 19.05,
    "pinDiameter": 9.53,
    "innerPlateHeight": 30,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2120",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport S-type (Kleine rol)",
    "strandsCount": 1,
    "pitch": 76.2,
    "width": 25.4,
    "rollerDiameter": 22.23,
    "pinDiameter": 11.11,
    "innerPlateHeight": 36,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2160",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport S-type (Kleine rol)",
    "strandsCount": 1,
    "pitch": 101.6,
    "width": 31.75,
    "rollerDiameter": 28.58,
    "pinDiameter": 14.27,
    "innerPlateHeight": 48,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2042",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport R-type (Grote draagrol)",
    "strandsCount": 1,
    "pitch": 25.4,
    "width": 7.94,
    "rollerDiameter": 15.88,
    "pinDiameter": 3.96,
    "innerPlateHeight": 12,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2052",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport R-type (Grote draagrol)",
    "strandsCount": 1,
    "pitch": 31.75,
    "width": 9.53,
    "rollerDiameter": 19.05,
    "pinDiameter": 5.08,
    "innerPlateHeight": 15,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2062",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport R-type (Grote draagrol)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 12.7,
    "rollerDiameter": 22.23,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2082",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport R-type (Grote draagrol)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 15.88,
    "rollerDiameter": 28.58,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2102",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport R-type (Grote draagrol)",
    "strandsCount": 1,
    "pitch": 63.5,
    "width": 19.05,
    "rollerDiameter": 39.68,
    "pinDiameter": 9.53,
    "innerPlateHeight": 30,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2122",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport R-type (Grote draagrol)",
    "strandsCount": 1,
    "pitch": 76.2,
    "width": 25.4,
    "rollerDiameter": 44.45,
    "pinDiameter": 11.11,
    "innerPlateHeight": 36,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2162",
    "norm": "Double Pitch Conveyor",
    "strand": "Transport R-type (Grote draagrol)",
    "strandsCount": 1,
    "pitch": 101.6,
    "width": 31.75,
    "rollerDiameter": 57.15,
    "pinDiameter": 14.27,
    "innerPlateHeight": 48,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2060H",
    "norm": "Double Pitch Heavy",
    "strand": "Transport Zwaar (S-type)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 12.7,
    "rollerDiameter": 11.91,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2062H",
    "norm": "Double Pitch Heavy",
    "strand": "Transport Zwaar (R-type Draagrol)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 12.7,
    "rollerDiameter": 22.23,
    "pinDiameter": 5.94,
    "innerPlateHeight": 18,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2080H",
    "norm": "Double Pitch Heavy",
    "strand": "Transport Zwaar (S-type)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 15.88,
    "rollerDiameter": 15.88,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "C2082H",
    "norm": "Double Pitch Heavy",
    "strand": "Transport Zwaar (R-type Draagrol)",
    "strandsCount": 1,
    "pitch": 50.8,
    "width": 15.88,
    "rollerDiameter": 28.58,
    "pinDiameter": 7.92,
    "innerPlateHeight": 24,
    "illustrationImg": "chain-double-pitch.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M20",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (20 kN breuklast)",
    "strandsCount": 1,
    "pitch": 50,
    "width": 16,
    "rollerDiameter": 25,
    "pinDiameter": 6,
    "innerPlateHeight": 25,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M28",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (28 kN breuklast)",
    "strandsCount": 1,
    "pitch": 63,
    "width": 18,
    "rollerDiameter": 30,
    "pinDiameter": 7,
    "innerPlateHeight": 30,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M40",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (40 kN breuklast)",
    "strandsCount": 1,
    "pitch": 80,
    "width": 20,
    "rollerDiameter": 36,
    "pinDiameter": 8,
    "innerPlateHeight": 35,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M56",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (56 kN breuklast)",
    "strandsCount": 1,
    "pitch": 100,
    "width": 24,
    "rollerDiameter": 42,
    "pinDiameter": 10,
    "innerPlateHeight": 40,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M80",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (80 kN breuklast)",
    "strandsCount": 1,
    "pitch": 125,
    "width": 28,
    "rollerDiameter": 50,
    "pinDiameter": 12,
    "innerPlateHeight": 50,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M112",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (112 kN breuklast)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 32,
    "rollerDiameter": 60,
    "pinDiameter": 15,
    "innerPlateHeight": 60,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M160",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (160 kN breuklast)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 37,
    "rollerDiameter": 70,
    "pinDiameter": 18,
    "innerPlateHeight": 70,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M224",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (224 kN breuklast)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 43,
    "rollerDiameter": 85,
    "pinDiameter": 21,
    "innerPlateHeight": 80,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M315",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (315 kN breuklast)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 48,
    "rollerDiameter": 100,
    "pinDiameter": 25,
    "innerPlateHeight": 90,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M450",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (450 kN breuklast)",
    "strandsCount": 1,
    "pitch": 250,
    "width": 56,
    "rollerDiameter": 120,
    "pinDiameter": 30,
    "innerPlateHeight": 100,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M630",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (630 kN breuklast)",
    "strandsCount": 1,
    "pitch": 315,
    "width": 65,
    "rollerDiameter": 140,
    "pinDiameter": 36,
    "innerPlateHeight": 120,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "M900",
    "norm": "DIN 8167 / ISO 1977",
    "strand": "Massieve pen (900 kN breuklast)",
    "strandsCount": 1,
    "pitch": 400,
    "width": 78,
    "rollerDiameter": 170,
    "pinDiameter": 44,
    "innerPlateHeight": 140,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "MT40",
    "norm": "DIN 8167 Holle Pen",
    "strand": "Holle pen (40 kN breuklast)",
    "strandsCount": 1,
    "pitch": 80,
    "width": 20,
    "rollerDiameter": 36,
    "pinDiameter": 12,
    "innerPlateHeight": 35,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "MT56",
    "norm": "DIN 8167 Holle Pen",
    "strand": "Holle pen (56 kN breuklast)",
    "strandsCount": 1,
    "pitch": 100,
    "width": 24,
    "rollerDiameter": 42,
    "pinDiameter": 14,
    "innerPlateHeight": 40,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "MT80",
    "norm": "DIN 8167 Holle Pen",
    "strand": "Holle pen (80 kN breuklast)",
    "strandsCount": 1,
    "pitch": 125,
    "width": 28,
    "rollerDiameter": 50,
    "pinDiameter": 16.5,
    "innerPlateHeight": 50,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "MT112",
    "norm": "DIN 8167 Holle Pen",
    "strand": "Holle pen (112 kN breuklast)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 32,
    "rollerDiameter": 60,
    "pinDiameter": 20.5,
    "innerPlateHeight": 60,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "MT160",
    "norm": "DIN 8167 Holle Pen",
    "strand": "Holle pen (160 kN breuklast)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 37,
    "rollerDiameter": 70,
    "pinDiameter": 24.5,
    "innerPlateHeight": 70,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "MT224",
    "norm": "DIN 8167 Holle Pen",
    "strand": "Holle pen (224 kN breuklast)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 43,
    "rollerDiameter": 85,
    "pinDiameter": 28.5,
    "innerPlateHeight": 80,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "MT315",
    "norm": "DIN 8167 Holle Pen",
    "strand": "Holle pen (315 kN breuklast)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 48,
    "rollerDiameter": 100,
    "pinDiameter": 33.5,
    "innerPlateHeight": 90,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV40",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (40 kN)",
    "strandsCount": 1,
    "pitch": 63,
    "width": 18,
    "rollerDiameter": 30,
    "pinDiameter": 10,
    "innerPlateHeight": 35,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV63",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (63 kN)",
    "strandsCount": 1,
    "pitch": 100,
    "width": 22,
    "rollerDiameter": 40,
    "pinDiameter": 12,
    "innerPlateHeight": 40,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV90",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (90 kN)",
    "strandsCount": 1,
    "pitch": 125,
    "width": 25,
    "rollerDiameter": 48,
    "pinDiameter": 14,
    "innerPlateHeight": 45,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV112",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (112 kN)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 30,
    "rollerDiameter": 55,
    "pinDiameter": 16,
    "innerPlateHeight": 50,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV140",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (140 kN)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 35,
    "rollerDiameter": 65,
    "pinDiameter": 18,
    "innerPlateHeight": 60,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV180",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (180 kN)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 45,
    "rollerDiameter": 80,
    "pinDiameter": 20,
    "innerPlateHeight": 70,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV250",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (250 kN)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 55,
    "rollerDiameter": 90,
    "pinDiameter": 26,
    "innerPlateHeight": 80,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV315",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (315 kN)",
    "strandsCount": 1,
    "pitch": 250,
    "width": 65,
    "rollerDiameter": 100,
    "pinDiameter": 30,
    "innerPlateHeight": 90,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV400",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (400 kN)",
    "strandsCount": 1,
    "pitch": 250,
    "width": 70,
    "rollerDiameter": 120,
    "pinDiameter": 36,
    "innerPlateHeight": 100,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FV500",
    "norm": "DIN 8165 Heavy Conveyor",
    "strand": "Zware transportketting (500 kN)",
    "strandsCount": 1,
    "pitch": 315,
    "width": 80,
    "rollerDiameter": 140,
    "pinDiameter": 42,
    "innerPlateHeight": 120,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FVC63",
    "norm": "DIN 8165 Holle Pen",
    "strand": "Holle pen zware serie (63 kN)",
    "strandsCount": 1,
    "pitch": 100,
    "width": 22,
    "rollerDiameter": 40,
    "pinDiameter": 18,
    "innerPlateHeight": 40,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FVC90",
    "norm": "DIN 8165 Holle Pen",
    "strand": "Holle pen zware serie (90 kN)",
    "strandsCount": 1,
    "pitch": 125,
    "width": 25,
    "rollerDiameter": 48,
    "pinDiameter": 20,
    "innerPlateHeight": 45,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FVC112",
    "norm": "DIN 8165 Holle Pen",
    "strand": "Holle pen zware serie (112 kN)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 30,
    "rollerDiameter": 55,
    "pinDiameter": 22,
    "innerPlateHeight": 50,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FVC140",
    "norm": "DIN 8165 Holle Pen",
    "strand": "Holle pen zware serie (140 kN)",
    "strandsCount": 1,
    "pitch": 160,
    "width": 35,
    "rollerDiameter": 65,
    "pinDiameter": 26,
    "innerPlateHeight": 60,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FVC180",
    "norm": "DIN 8165 Holle Pen",
    "strand": "Holle pen zware serie (180 kN)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 45,
    "rollerDiameter": 80,
    "pinDiameter": 30,
    "innerPlateHeight": 70,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FVC250",
    "norm": "DIN 8165 Holle Pen",
    "strand": "Holle pen zware serie (250 kN)",
    "strandsCount": 1,
    "pitch": 200,
    "width": 55,
    "rollerDiameter": 90,
    "pinDiameter": 36,
    "innerPlateHeight": 80,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "FVC315",
    "norm": "DIN 8165 Holle Pen",
    "strand": "Holle pen zware serie (315 kN)",
    "strandsCount": 1,
    "pitch": 250,
    "width": 65,
    "rollerDiameter": 100,
    "pinDiameter": 42,
    "innerPlateHeight": 90,
    "illustrationImg": "chain-conveyor-m.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 812",
    "norm": "Slatband (Staal)",
    "strand": "Enkel Scharnier (82.5 mm breedte)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 3,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 815",
    "norm": "Slatband (RVS)",
    "strand": "RVS Enkel Scharnier (82.5 mm)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 3,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 802",
    "norm": "Slatband (Staal)",
    "strand": "Dubbel Scharnier (190.5 mm breedte)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 190.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 3,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 805",
    "norm": "Slatband (RVS)",
    "strand": "RVS Dubbel Scharnier (190.5 mm)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 190.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 3,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 881",
    "norm": "Slatband (Staal Bocht)",
    "strand": "Bochtgangbaar met Tab",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 3,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 8811",
    "norm": "Slatband (Staal Bocht)",
    "strand": "Bochtgangbaar met Magneet",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 3,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 820",
    "norm": "Slatband (Kunststof POM)",
    "strand": "Rechtlopend Kunststof (82.5 mm)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 4,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie LF820",
    "norm": "Slatband (Low Friction POM)",
    "strand": "Low Friction Kunststof (82.5 mm)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 4,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 880",
    "norm": "Slatband (Kunststof POM Bocht)",
    "strand": "Bochtlopend met Tab",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 4,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 882",
    "norm": "Slatband (Kunststof POM Bocht)",
    "strand": "Bochtlopend Zwaar (190.5 mm)",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 190.5,
    "rollerDiameter": 0,
    "pinDiameter": 7.94,
    "innerPlateHeight": 4.5,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Serie 879",
    "norm": "Slatband (Kunststof POM Bocht)",
    "strand": "Bochtlopend Beveled",
    "strandsCount": 1,
    "pitch": 38.1,
    "width": 82.5,
    "rollerDiameter": 0,
    "pinDiameter": 6.35,
    "innerPlateHeight": 4,
    "illustrationImg": "chain-slatband.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (4x12)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 12,
    "width": 5.2,
    "rollerDiameter": 4,
    "pinDiameter": 4,
    "innerPlateHeight": 4,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (5x15)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 15,
    "width": 6.5,
    "rollerDiameter": 5,
    "pinDiameter": 5,
    "innerPlateHeight": 5,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (6x18)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 18,
    "width": 7.8,
    "rollerDiameter": 6,
    "pinDiameter": 6,
    "innerPlateHeight": 6,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (7x21)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 21,
    "width": 9.1,
    "rollerDiameter": 7,
    "pinDiameter": 7,
    "innerPlateHeight": 7,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (8x24)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 24,
    "width": 10.4,
    "rollerDiameter": 8,
    "pinDiameter": 8,
    "innerPlateHeight": 8,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (10x30)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 30,
    "width": 13,
    "rollerDiameter": 10,
    "pinDiameter": 10,
    "innerPlateHeight": 10,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (13x39)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 39,
    "width": 16.9,
    "rollerDiameter": 13,
    "pinDiameter": 13,
    "innerPlateHeight": 13,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (16x48)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 48,
    "width": 20.8,
    "rollerDiameter": 16,
    "pinDiameter": 16,
    "innerPlateHeight": 16,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (18x54)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 54,
    "width": 23.4,
    "rollerDiameter": 18,
    "pinDiameter": 18,
    "innerPlateHeight": 18,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (20x60)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 60,
    "width": 26,
    "rollerDiameter": 20,
    "pinDiameter": 20,
    "innerPlateHeight": 20,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (22x66)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 66,
    "width": 28.6,
    "rollerDiameter": 22,
    "pinDiameter": 22,
    "innerPlateHeight": 22,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (26x78)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 78,
    "width": 33.8,
    "rollerDiameter": 26,
    "pinDiameter": 26,
    "innerPlateHeight": 26,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 80 (32x96)",
    "norm": "Ronde Schalm (EN 818-2)",
    "strand": "Grade 80 Hijsketting",
    "strandsCount": 1,
    "pitch": 96,
    "width": 41.6,
    "rollerDiameter": 32,
    "pinDiameter": 32,
    "innerPlateHeight": 32,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 100 (6x18)",
    "norm": "Ronde Schalm (EN 818-4)",
    "strand": "Grade 100 Hoogwaardig",
    "strandsCount": 1,
    "pitch": 18,
    "width": 7.8,
    "rollerDiameter": 6,
    "pinDiameter": 6,
    "innerPlateHeight": 6,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 100 (8x24)",
    "norm": "Ronde Schalm (EN 818-4)",
    "strand": "Grade 100 Hoogwaardig",
    "strandsCount": 1,
    "pitch": 24,
    "width": 10.4,
    "rollerDiameter": 8,
    "pinDiameter": 8,
    "innerPlateHeight": 8,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 100 (10x30)",
    "norm": "Ronde Schalm (EN 818-4)",
    "strand": "Grade 100 Hoogwaardig",
    "strandsCount": 1,
    "pitch": 30,
    "width": 13,
    "rollerDiameter": 10,
    "pinDiameter": 10,
    "innerPlateHeight": 10,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 100 (13x39)",
    "norm": "Ronde Schalm (EN 818-4)",
    "strand": "Grade 100 Hoogwaardig",
    "strandsCount": 1,
    "pitch": 39,
    "width": 16.9,
    "rollerDiameter": 13,
    "pinDiameter": 13,
    "innerPlateHeight": 13,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 100 (16x48)",
    "norm": "Ronde Schalm (EN 818-4)",
    "strand": "Grade 100 Hoogwaardig",
    "strandsCount": 1,
    "pitch": 48,
    "width": 20.8,
    "rollerDiameter": 16,
    "pinDiameter": 16,
    "innerPlateHeight": 16,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 120 (8x24)",
    "norm": "Ronde Schalm (EN 818)",
    "strand": "Grade 120 Ultrasterk",
    "strandsCount": 1,
    "pitch": 24,
    "width": 10.4,
    "rollerDiameter": 8,
    "pinDiameter": 8,
    "innerPlateHeight": 8,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 120 (10x30)",
    "norm": "Ronde Schalm (EN 818)",
    "strand": "Grade 120 Ultrasterk",
    "strandsCount": 1,
    "pitch": 30,
    "width": 13,
    "rollerDiameter": 10,
    "pinDiameter": 10,
    "innerPlateHeight": 10,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  },
  {
    "designation": "Grade 120 (13x39)",
    "norm": "Ronde Schalm (EN 818)",
    "strand": "Grade 120 Ultrasterk",
    "strandsCount": 1,
    "pitch": 39,
    "width": 16.9,
    "rollerDiameter": 13,
    "pinDiameter": 13,
    "innerPlateHeight": 13,
    "illustrationImg": "chain-round-link.png",
    "dimensionsImg": "chain-dimensions.png"
  }
];
